# Generated by Django 5.0.1 on 2024-04-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_alunos_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'alunos_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('campus', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cursos_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cursos_materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('carga_horaria', models.CharField(max_length=20)),
                ('prof_id', models.IntegerField()),
            ],
            options={
                'db_table': 'materias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('RP', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'professores',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='alunos',
            table='alunos',
        ),
    ]
