# Generated by Django 5.0.1 on 2024-04-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0003_alunos_materia_cursos_cursos_materia_materias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='professores_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'professores_materia',
                'managed': False,
            },
        ),
    ]
