# Generated by Django 5.0.1 on 2024-04-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('RA', models.CharField(max_length=30)),
                ('curso_id', models.IntegerField()),
            ],
        ),
    ]
