# Generated by Django 5.0.1 on 2024-04-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alunos',
            options={'managed': False},
        ),
    ]
